### ISSUE TITLE
oxidized-1.5.2 is not compatible with betterend and better nether

### ISSUE THREAD

**Issue by rbroderi** [Safrodev/oxidized#16] opened 2021-12-31 04:17 UTC
when this version is installed the better end and better nether ores no longer drop their ores.

**Comment by rbroderi** [comment] 2021-12-31 04:36
also seems to be the oxidized-1.5.1 version. only the oxidized-1.5.0 version seems to work

**Comment by Safrodev** [comment] 2021-12-31 14:18
Uh that’s strange, oxidized should not be interfering with ore drops from other mods. Is there any sort of log/error output and are you certain the problem is from this mod?

**Comment by rbroderi** [comment] 2021-12-31 14:28
I am certain as i have tested on a new world with and without oxidized 1.5.2 and 1.5.1 vs 1.5.0 and they cause the mod ores to not drop. Unfortunately no error in logs that i can see. I will try to do further investigation as time permits.

**Comment by ShockPuppet** [comment] 2022-01-03 01:18
Im using Oxidised 1.5.2 with Better End and Better Nether (latest versions) and the ores are dropping just fine for me. Have a few hundred mods installed.

**Comment by Safrodev** [comment] 2022-01-07 00:41
I did some testing myself, it seems to work completely fine. Please double check if the issue is from this mod, otherwise I am closing the issue.

**Closed by Safrodev** 2022-01-07 00:41 UTC
